name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    # - name: Testing....display available Xcodes on the Server
    #   run: ls /Applications | grep Xcode

    # - name: List all simulators
    #   run: xcrun simctl list
    
    # - name: Select Xcode
    #   run: sudo xcode-select -switch /Applications/Xcode_12.app

    - name: List all destinations
      run: xcodebuild -project Todo.xcodeproj -scheme CI -showdestinations

    # - name: Build and test
    #   run: xcodebuild clean build test -project Todo.xcodeproj -scheme "CI" -sdk iphonesimulator -destination "generic/platform=iOS Simulator" ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO
    - name: Compile and run tests
      run: fastlane scan --scheme "CI"