name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_12.5.1.app

    - name: Build and test
      run: xcodebuild clean build test -project Todo.xcodeproj -scheme CI -sdk iphonesimulator -destination "platform=iOS Simulator,OS=14.5,name=iPhone 12 Pro" ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO