name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    # - name: Testing....display available Xcodes on the Server
    #   run: ls /Applications | grep Xcode

    - name: List all simulators
      run: xcrun simctl list
    
    - name: Select Xcode Version
      run: sudo xcode-select -switch /Applications/Xcode_12.4.0.app

    - name: Build and test
      run: xcodebuild clean build test -project Todo.xcodeproj -scheme Todo -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 12 Pro" ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO