name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:

    runs-on: macos-12

    steps:
    - uses: actions/checkout@v2

    - name: Compile and run tests
      run: fastlane scan --project "Todo.xcodeproj" --scheme "CI" ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO