name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    # - name: Testing....display available Xcodes on the Server
    #   run: ls /Applications | grep Xcode
    
    - name: Select Xcode Version
      run: sudo xcode-select -switch /Applications/Xcode_12.4.0.app

    - name: Build and test
      run: xcodebuild clean build test -project Todo.xcodeproj -scheme CI -sdk iphonesimulator -destination "platform=iOS Simulator,id=6848AD49-7FE1-41CA-93AE-2F96474F6BB3" ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO